version: "3"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "4001:4000"
    environment:
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGHOST: $POSTGRES_HOST
      PGPORT: 5432
    depends_on:
      - postgres
    command:
      - "./entrypoint.sh"
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
