version: '3.8'

services:
  app:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGHOST: $POSTGRES_HOST
      PGPORT: $POSTGRES_PORT
    depends_on:
      - postgres
    volumes:
      - ./service_account.json:/app/service_account.json

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./_pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
       - "80:80"
